### ISSUE TITLE
Broken link https://mobilefirstplatform.ibmcloud.com/2016/03/27/connecting-securely-from-ibm-mobilefirst-platform-foundation-on-bluemix-to-on-premises-systems/

### ISSUE THREAD

**Issue by srikanthkm** [MobileFirst-Platform-Developer-Center/DevCenter#1]
The above link is referenced from https://mobilefirstplatform.ibmcloud.com/blog/2016/03/31/mobile-foundation-bluemix-beta/

but the page is not found.

**Comment by IdanAdar** [comment]
Fixed. Check again in a few minutes.
