### ISSUE TITLE
Push notifications tutorial link Issue

### ISSUE THREAD

**Issue by AparnaMylavarapu** [MobileFirst-Platform-Developer-Center/DevCenter#14]
Hi,

I am not able to open the below link:
[https://mobilefirstplatform.ibmcloud.com/tutorials/en/foundation/8.0/notifications/sending-push-notifications/]

**Comment by IdanAdar** [comment]
The correct location is here: https://mobilefirstplatform.ibmcloud.com/tutorials/en/foundation/8.0/notifications/sending-notifications/

Where did you find the link you mentioned in your question?

**Comment by AparnaMylavarapu** [comment]
Thanks for the link.

The link is in MFP 8.0 console.
Project--->push-->push settings-->
Configure your push notifications here. For detailed instructions, see the **tutorial about push notifications.**

**Comment by IdanAdar** [comment]
Right. Thanks. I'll put a redirect in place while we update the link in the console.
