### ISSUE TITLE
JSONStore can't pass the xcode build.

### ISSUE THREAD

**Issue by simon1118** [MobileFirst-Platform-Developer-Center/DevCenter#18]
It gives me the following errors when tried to build app after I added JSONStore plugin:

duplicate symbol _OBJC_CLASS_$_StoragePlugin in:
    MFPStarterCordova/Plugins/cordova-plugin-mfp/IBMMobileFirstPlatformFoundationHybrid.framework/IBMMobileFirstPlatformFoundationHybrid(StoragePlugin.o)
    MFPStarterCordova/Plugins/cordova-plugin-mfp-jsonstore/IBMMobileFirstPlatformFoundationHybridJSONStore.framework/IBMMobileFirstPlatformFoundationHybridJSONStore(StoragePlugin.o)
duplicate symbol _OBJC_METACLASS_$_StoragePlugin in:
    MFPStarterCordova/Plugins/cordova-plugin-mfp/IBMMobileFirstPlatformFoundationHybrid.framework/IBMMobileFirstPlatformFoundationHybrid(StoragePlugin.o)
    MFPStarterCordova/Plugins/cordova-plugin-mfp-jsonstore/IBMMobileFirstPlatformFoundationHybridJSONStore.framework/IBMMobileFirstPlatformFoundationHybridJSONStore(StoragePlugin.o)
duplicate symbol _OBJC_IVAR_$_StoragePlugin._operationQueue in:
    MFPStarterCordova/Plugins/cordova-plugin-mfp/IBMMobileFirstPlatformFoundationHybrid.framework/IBMMobileFirstPlatformFoundationHybrid(StoragePlugin.o)
    MFPStarterCordova/Plugins/cordova-plugin-mfp-jsonstore/IBMMobileFirstPlatformFoundationHybridJSONStore.framework/IBMMobileFirstPlatformFoundationHybridJSONStore(StoragePlugin.o)
ld: 3 duplicate symbols for architecture x86_64

**Comment by IdanAdar** [comment]
Hi, to which sample are you referring to?

**Comment by simon1118** [comment]
I just followed the guide here: https://mobilefirstplatform.ibmcloud.com/tutorials/en/foundation/8.0/application-development/jsonstore/cordova/
and I also install the sqlite3 plugin as JSONStore plugin needed with command 
_sudo cordova plugin add cordova-sqlite-storage_

**Comment by IdanAdar** [comment]
Please open this issue in the correct location: https://github.com/MobileFirst-Platform-Developer-Center/JSONStoreCordova/tree/release80
