### ISSUE TITLE
The NTLM Authentication page missing

### ISSUE THREAD

**Issue by rgara001** [MobileFirst-Platform-Developer-Center/DevCenter#2]
The developer page for the NTLM tutorial is missing. Please advise.
https://mobilefirstplatform.ibmcloud.com/tutorials/en/foundation/7.1/authentication-security/ntlm-authentication/

**Comment by NathanHazout** [comment]
Hi,
The correct link is: https://mobilefirstplatform.ibmcloud.com/tutorials/en/foundation/7.1/advanced-topics/ntlm-authentication/

However I would like to know how you arrived at the broken link (google, stackoverflow, bookmark, etc) so we can avoid this from happening in the future.

Thanks!

**Comment by rgara001** [comment]
Thank you!

I googled "ntlm mobilefirst" and it is the first result returned.
https://www.google.com/search?q=ntlm+mobilefirst&ie=utf-8&oe=utf-8

**Comment by rgara001** [comment]
@nasht00 please let me know if i should close the issue.

Also, I was actually looking for a tutorial for an adapter that accepts NTLM protocol username & password, rather than an adapter that sends it to a server as the tutorial instructs.

**Comment by IdanAdar** [comment]
@nasht00 , I think it is a mishap at re-creating the tutorials structure. This should indeed be in authentication-security.

**Comment by IdanAdar** [comment]
Corrected the tutorial location. Will be live in a few minutes.
