### ISSUE TITLE
link to API reference

### ISSUE THREAD

**Issue by mbillau** [MobileFirst-Platform-Developer-Center/DevCenter#20]
there are numerous places in the documentation with phrases like:
"See the API Reference for “MFP.Server.invokeHttp” in the user documentation for a complete list of options."

However, there does not seem to be a link to the API reference anywhere, not on the sidebar or in this text, which means people have to then search Google. We should have a top level link on the left to the main API page and then link to specific pages within the API when we have these types of phrases.

**Comment by mbillau** [comment]
Wait, maybe this isn't relevant if we are moving the API Reference into the DevCenter. I forgot that was happening...

**Comment by IdanAdar** [comment]
That's right. We plan to migrate the API reference in the near future.
