### ISSUE TITLE
Broken links for MobileFirst 8 documentation

### ISSUE THREAD

**Issue by gianlucainnocente** [MobileFirst-Platform-Developer-Center/DevCenter#21]
Hi,
i have some problems with the Mobile First 8.0 documentation, infact all links are broken.
For example, this links returns a 404 error: https://mobilefirstplatform.ibmcloud.com/tutorials/en/foundation/8.0/upgrading/migrating-adapters

Can you check please?

Thank you

**Comment by IdanAdar** [comment]
Our hosting is currently experiencing some difficulties. If you will refresh the page it will work and sometimes not work. This is true to the entire website.

**Comment by gianlucainnocente** [comment]
Thank you.
Now using nodeJS, when i try the "npm install -g mfpdev-cli" command, i got this error:

fetch failed https://registry.npmjs.org/ibm-strings/-/ibm-strings-0.1.4.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404


Why?
Thank you

**Comment by IdanAdar** [comment]
I can't help you with that question... You will need to open a support ticket (PMR) for this. It is not related to the website itself.

The frequent failure in page loading in the website has been resolved.
