### ISSUE TITLE
FWLSE3000E: A server error was detected.

### ISSUE THREAD

**Issue by psacchitella** [MobileFirst-Platform-Developer-Center/DevCenter#25]
com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 8 path $

I have submitted a ticket, escalated it and still not fixed.
I have this issue on my old Bluemix instance on dev and a brand new one on a different domain.

My development team at Watson Health really needs this functional.

![mbstillbrokeasalways](https://cloud.githubusercontent.com/assets/877556/22308820/8e13a0cc-e316-11e6-9bda-c9c5ab979d16.png)

also this link doesn't work:
https://mobilefirstplatform.ibmcloud.com/tutorials/en/foundation/8.0/notifications/sending-push-notifications/
![01252017bmfail2](https://cloud.githubusercontent.com/assets/877556/22308876/d52abc48-e316-11e6-9009-539e3d6ab963.png)

**Comment by IdanAdar** [comment]
Hi, where from are you trying to reach that location when you get the 404?

As for your technical issue I'm sorry but this is not the place for it. This is for issues with the developer center. I suggest that you will escalate your issue through IBM internal channels.

**Comment by IdanAdar** [comment]
Ah I see. Yes, this should be fixed in an upcoming iFix.
The correct link to use is: https://mobilefirstplatform.ibmcloud.com/tutorials/en/foundation/8.0/notifications/sending-notifications/

**Comment by psacchitella** [comment]
I have, for several days.  It is okay, the link is the one on the first image "tutorial about push notifications". Any idea on the timeline?

**Comment by IdanAdar** [comment]
Hopefully by the end of the month.

**Comment by psacchitella** [comment]
Okay, thank you. As always I appreciate the help.
