### ISSUE TITLE
Missing adapter documentation for MFP 8.0

### ISSUE THREAD

**Issue by ibmjm** [MobileFirst-Platform-Developer-Center/DevCenter#27]
The MFP 8.0 Operations Centre has a dead link: https://mobilefirstplatform.ibmcloud.com/tutorials/en/foundation/8.0/adapters/adapters-overview/

**Comment by IdanAdar** [comment]
@sreelathasankaranarayanan, please notify the Console team that the mentioned URL above should change to this one: https://mobilefirstplatform.ibmcloud.com/tutorials/en/foundation/8.0/adapters/

@ibmjm I am closing this issue as this is the wrong place to report this (this org is about the samples and documentation, not the product itself). If you choose so you can also open a PMR...

**Comment by ibmjm** [comment]
@IdanAdar , :+1:  for getting on top of this and passing to the right people.  However, (and this is **definitely** a documentation topic) I cannot seem to follow alternative instructions in the [Deploy an Adapter](https://mobilefirstplatform.ibmcloud.com/tutorials/en/foundation/8.0/quick-start/ios/#4-deploy-an-adapter) section.  I've downloaded the sample adapter zip file but there's no instruction for _where_ to unzip it before trying to run the `mfpdev adapter build`, nor if the file needs to be modified before it can be built.  That was where I got the error message with the bad link that I started this report with.
If there's another resource I can go to for information specifically about how to build the sample adapter so I can continue with the MFP tutorial that would be terrific. :)

In case you see this and ask what error I got, this is my output:
`jons-mbp:~/Documents/MyFirstSwiftMFPapp/javaAdapter $ mfpdev adapter build
Building adapter...

[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.ibm.mfp.sample:javaAdapter:adapter:1.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for com.ibm.mfp:adapter-maven-plugin is missing. @ line 44, column 12
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building javaAdapter 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for com.ibm.mfp:mfp-security-checks-base:jar:8.0.2017011114 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.511 s
[INFO] Finished at: 2017-03-28T16:32:31-04:00
[INFO] Final Memory: 7M/155M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project javaAdapter: Could not resolve dependencies for project com.ibm.mfp.sample:javaAdapter:adapter:1.0-SNAPSHOT: Failure to find com.ibm.mfp:mfp-security-checks-base:jar:8.0.2017011114 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

Error building adapter
undefined
Error: An error occurred during an attempt to build the adapter. See the preceding messages for details.
jons-mbp:~/Documents/MyFirstSwiftMFPapp/javaAdapter $ `

**Comment by IdanAdar** [comment]
FYI, I am no longer in the Foundation team.

> I've downloaded the sample adapter zip file but there's no instruction for where to unzip it before trying to run the mfpdev adapter build

The location of the .zip file does not matter.
You need to:
1. Unzip
2. Navigate into the folder
3. Run `mfpdev adapter build` > `mfpdev adapter deploy`.

Deployment uses the server profile (that is set to "default"), defined in the CLI: `mfpdev server info` . For whatever reason the sample adapter provided in the console is not working and I suggest to open a PMR about this.

What you can do to overcome this, is create your own adapter using the CLI. Maybe that will work better. Run: `mfpdev adapter create`. More information on creating adapters here: https://mobilefirstplatform.ibmcloud.com/tutorials/en/foundation/8.0/adapters/creating-adapters/

@sreelathasankaranarayanan, please involve a team member.

**Comment by ibmjm** [comment]
@IdanAdar thanks for your commentary and suggestions.
