### ISSUE TITLE
Incompatibility issue of test workbench with mobilefirst 8.0

### ISSUE THREAD

**Issue by shalinisingh2610** [MobileFirst-Platform-Developer-Center/DevCenter#28]
Hi ,

I am trying to test my cordova application(mobile first 8.0) with IBM Mobilefirst test workbench 8.7.
But when I am trying to add my android application's .apk file it shows error.
Please refer the below link for the error screenshot
![image](https://cloud.githubusercontent.com/assets/26960554/24747907/7cdd05ee-1adb-11e7-8405-fd8f8a8c41fb.png)

**Comment by IdanAdar** [comment]
Using Workbench is not supported by MobileFirst Foundation 8.0.
