### ISSUE TITLE
Unable to run application 

### ISSUE THREAD

**Issue by pragya2611** [MobileFirst-Platform-Developer-Center/DevCenter#33]
Hi Team , 

I am new to MobileFirst development foundation 8. I have installed cli , android sdk , cordova cli and started server on my end . 
I have environment variables set for Android SDK tools and have installed build_tools. 
I ran mfpdev app register , the app got registered . But when I run mfpdev app preview , I get error 
"the specified platform version is invalid for platform 'android'". 
How can this be resolved at our end ?

![image](https://cloud.githubusercontent.com/assets/20012925/25843015/91807dc6-34c3-11e7-8090-94e47eb52b50.png)

**Comment by sreelathasankaranarayanan** [comment]
@pragya2611 Please join our slack channel to get resolution to your issue. Git issues are opened only for fixes required on the Devcenter documentation. https://mobilefirstplatform.ibmcloud.com/blog/2017/05/26/come-chat-with-us/

Closing this issue as this is not the right place to discuss this issue.
