### ISSUE TITLE
The live update help link is not working

### ISSUE THREAD

**Issue by ShinojEdakkara** [MobileFirst-Platform-Developer-Center/DevCenter#35]
When clicking on 'Developer Center' link under the section "Live Update" , it gives 404.

https://mobilefirstplatform.ibmcloud.com/tutorials/en/foundation/8.0/using-the-mfpf-sdk/live-update/

**Comment by sreelathasankaranarayanan** [comment]
The link needs to be corrected in operations console, the correct url would be https://mobilefirstplatform.ibmcloud.com/tutorials/en/foundation/8.0/application-development/live-update/
Closing this git issue as this is not a Devcenter issue.
