### ISSUE TITLE
Page not found 404 error

### ISSUE THREAD

**Issue by yingzhao** [MobileFirst-Platform-Developer-Center/DevCenter#39]
This page, https://mobilefirstplatform.ibmcloud.com/tutorials/ru/foundation/8.0/analytics/console/analytics-data-purge/,
does not exist any more. Could you let me know the correct replacement page for it? Thank you

**Comment by sreelathasankaranarayanan** [comment]
Please access the english version of the page from https://mobilefirstplatform.ibmcloud.com/tutorials/en/foundation/8.0/analytics/console/analytics-data-purge/, the translated version is currently not published.
