### ISSUE TITLE
unreachable url

### ISSUE THREAD

**Issue by prasadpandari** [MobileFirst-Platform-Developer-Center/DevCenter#4]
https://mobilefirstplatform.ibmcloud.com/tutorials/en/foundation/8.0/using-the-mfpf-sdk/jsonstore-cordova/
returns 404

**Comment by IdanAdar** [comment]
What page did you visit that led you there?
The correct link to use is https://mobilefirstplatform.ibmcloud.com/tutorials/en/foundation/8.0/using-the-mfpf-sdk/jsonstore/cordova/

**Comment by prasadpandari** [comment]
through google search

https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=ibm%20mobilefirst%20jsonstore%20on%20uwp

third result in google search

On Tue, May 10, 2016 at 6:36 AM, Idan Adar notifications@github.com wrote:

> What page did you visit that led you there?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/MobileFirst-Platform-Developer-Center/DevCenter/issues/4#issuecomment-218132274

## 

Thanks,
Prasad
408 679 3833

**Comment by IdanAdar** [comment]
Thanks. The tutorial location recently changed to the URL I mentioned in my previous comment.
I will put a redirect in place. Please use the mentioned URL.
