### ISSUE TITLE
Elasticsearch version in the Overview section is wrong

### ISSUE THREAD

**Issue by KrishnaChandrasekar** [MobileFirst-Platform-Developer-Center/DevCenter#41]
The elasticsearch embedded within the analytics 8.0 is 1.7.5, where as the documentation says it is "1.5x"

This needs to be corrected to "1.7.5"

https://mobilefirstplatform.ibmcloud.com/tutorials/en/foundation/8.0/analytics/elasticsearch/#overview

**Comment by sreelathasankaranarayanan** [comment]
Fixed the issue.
