### ISSUE TITLE
iOS app crashes if the running worklight version is expired

### ISSUE THREAD

**Issue by kamarshad** [MobileFirst-Platform-Developer-Center/DevCenter#44]
Hi @nasht00 @krckumar @sjimdickens @csantanapr  ,

My iOS app uses IBMMobileFirstPlatformFoundation. I am facing a weird issue at a particular point.
Actually we want to test a forcefull upgrade scenario if we want to mark any public iOS app version outdated so that we could ask our customer to update the installed iOS version from the app store. 

To do this, we just mark the MFP application version(worklightconsole) expired in and once we do it as soon the iOS app launched we start getting the forceful upgrade message along with the download URL. I verified this alert is triggered from the WLClient library itself we don't have access to that piece of code.

But here the issue is our app is getting crashed after that alert if we perform any activity in our app. We have a screen where we have mfp adapter calls (as these services are called on, again we get the same alert) but after such attempts app is getting crashed.

Here one of the crash logs

`WORKLIGHT] Uncaught Exception: *** -[__NSArrayM objectAtIndex:]: index 0 beyond bounds for empty array
2019-10-10 11:55:00.252534+0400 App_Name [810:52186] *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM objectAtIndex:]: index 0 beyond bounds for empty array' `
`

`
[Animation] +[UIView setAnimationsEnabled:] being called from a background thread. Performing any operation from a background thread on UIView or a subclass is not supported and may result in unexpected and insidious behavior. trace=(
	0   UIKitCore                           0x000000021c0e84d4 <redacted> + 116
	1   libdispatch.dylib                   0x0000000108040c74 _dispatch_client_callout + 16
	2   libdispatch.dylib                   0x0000000108042c84 _dispatch_once_callout + 84
	3   UIKitCore                           0x000000021c0e845c <redacted> + 100
	4   UIKitCore                           0x000000021c0e85c8 <redacted> + 92
	5   UIKitCore                           0x000000021b3c7fdc <redacted> + 152
	6   App_Name                         0x0000000103ec20a8 -[RemoteDisableChallengeHandler handleFailure:] + 1012
	7   App_Name                         0x0000000103eceb54 __43-[WLRequest processFailuresWithDictionary:]_block_invoke + 412
	8   CoreFoundation                      0x00000001ef72de4c <redacted> + 84
	9   App_Name                         0x0000000103ece984 -[WLRequest processFailuresWithDictionary:] + 160
	10  App_Name                         0x0000000103ee1a0c -[WLAuthorizationManager handleRedirectWithResponse:request:] + 1048
	11  App_Name                         0x0000000103eca56c -[WLRequest requestRedirected:] + 120
	12  App_Name                         0x0000000103e811ec -[WLAFHTTPRequestOperationManagerWrapper requestRedirected:response:] + 1136
	13  App_Name                         0x0000000103e7fd84 __47-[WLAFHTTPRequestOperationManagerWrapper start]_block_invoke240 + 148
	14  App_Name                         0x0000000103e47480 -[WLAFURLConnectionOperation connection:willSendRequest:redirectResponse:] + 244
	15  CoreFoundation                      0x00000001ef83fba0 <redacted> + 144
	16  CoreFoundation                      0x00000001ef721c90 <redacted> + 292
	17  CoreFoundation                      0x00000001ef7228c4 <redacted> + 60
	18  CoreFoundation                      0x00000001ef83da5c <redacted> + 636
	19  CoreFoundation                      0x00000001ef83f9fc _CF_forwarding_prep_0 + 92
	20  CFNetwork                           0x00000001f001396c <redacted> + 152
	21  CFNetwork                           0x00000001f00527b0 <redacted> + 60
	22  CFNetwork                           0x00000001efddd608 <redacted> + 196
	23  CFNetwork                           0x00000001efddd660 <redacted> + 56
	24  CFNetwork                           0x00000001f0012d90 <redacted> + 112
	25  CFNetwork                           0x00000001eff5dff8 <redacted> + 328
	26  CFNetwork                           0x00000001eff5d86c <redacted> + 108
	27  libdispatch.dylib                   0x0000000108040c74 _dispatch_client_callout + 16
	28  libdispatch.dylib                   0x0000000108044840 _dispatch_block_invoke_direct + 232
	29  CFNetwork                           0x00000001f0031b20 <redacted> + 36
	30  CoreFoundation                      0x00000001ef76b490 CFArrayApplyFunction + 80
	31  CFNetwork                           0x00000001f00319f0 <redacted> + 128
	32  CFNetwork                           0x00000001f0032b54 <redacted> + 312
	33  CFNetwork                           0x00000001f00328d0 <redacted> + 60
	34  CoreFoundation                      0x00000001ef7ca2bc <redacted> + 24
	35  CoreFoundation                      0x00000001ef7ca23c <redacted> + 88
	36  CoreFoundation                      0x00000001ef7c9b24 <redacted> + 176
	37  CoreFoundation                      0x00000001ef7c4a60 <redacted> + 1004
	38  CoreFoundation                      0x00000001ef7c4354 CFRunLoopRunSpecific + 436
	39  Foundation                          0x00000001f0191fcc <redacted> + 300
	40  Foundation                          0x00000001f01cd49c <redacted> + 88
	41  App_Name                         0x0000000103e41f4c +[WLAFURLConnectionOperation networkRequestThreadEntryPoint:] + 308
	42  Foundation                          0x00000001f02be6e4 <redacted> + 984
	43  libsystem_pthread.dylib             0x00000001ef4582c0 <redacted> + 128
	44  libsystem_pthread.dylib             0x00000001ef458220 _pthread_start + 44
	45  libsystem_pthread.dylib             0x00000001ef45bcdc thread_start + 4
)
`

`Uncaught Exception: Engine marked as needing optimization even though it's already in progress.
2019-10-10 12:34:30.871948+0400 APP_Name [860:60246] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Engine marked as needing optimization even though it's already in progress.`

`Uncaught Exception: Exercised class for selector implementation needs to be pushed
2019-10-10 12:49:18.786861+0400 APP_Name[898:64810] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Exercised class for selector implementation needs to be pushed'`

Other details

Worklight platformVersion --  **7.1.0**
iOS version -- **12.x**
 
It would be great if you guys can help me in this regard

**Comment by csantanapr** [comment]
From the exception nothing obvyI can point out. 

This repository is for a blog site, you will not get quick support here. 

I suggest you open a support ticket with ibm to get support and help with your problem.

**Comment by kamarshad** [comment]
Thank you for your kind reply. I have just raised a request for the MFP Dev Slack channel. Apart from this, I don't see any other way to get help from ibm team. 
Can you please guide me How can I open the support ticket with ibm?

**Comment by kamarshad** [comment]
@csantanapr Finally I got the joining request from MFP Dev slack channel.
I would share this issue there thank you once again for your help.
