### ISSUE TITLE
Download image urls in GridView using SQL Database

### ISSUE THREAD

**Issue by akshatajamdade** [MobileFirst-Platform-Developer-Center/DevCenter#5]
I want example of download image_urls with description in GridView(Image with Text)  from SQL database using web Service with HTTP URLConnection

**Comment by IdanAdar** [comment]
What?

**Comment by NathanHazout** [comment]
@akshatajamdade I think you opened this on the wrong project maybe by mistake?
This repository is regarding issues with this website: https://mobilefirstplatform.ibmcloud.com/
