### ISSUE TITLE
mfp-devkit-mac-0323-1719.zip not found

### ISSUE THREAD

**Issue by RazvanRaduIbm** [MobileFirst-Platform-Developer-Center/DevCenter#6]
Hi, 

I'm trying to download and install mfp-devkit-mac-***_-**_*.zip but I can't find it. 
We need to migrate from mfp 7.1.3 to 8.0 and can't find the devkit. I saw video tutorials about setting up but "Downloads" section says "Stay tuned"
Can you advise, please?

Thank you!

**Comment by IdanAdar** [comment]
As the text says, it is currently Not Available. Check back again soon to see if it has been released.
Until then, you can use the Mobile Foundation Bluemix service.

**Comment by RazvanRaduIbm** [comment]
Ok, I understand. 
Is there any other way to get up and running mfps 8.0 by using a Liberty Server? If so, is there any documentation about that? Thank you!
