### ISSUE TITLE
Can we use CLI to run a command like we use Eclipse(Build all environment)?

### ISSUE THREAD

**Issue by Hamasn** [MobileFirst-Platform-Developer-Center/DevCenter#8]
I am using MFP 7.1 for our commercial project ,due to some reason, now we are using android studio andXCode as our environment to develop(Android client and iOS client),So eclipse is only used to "build all", is there any command that we can use to build all by CLI Command ,I tried 
`

> cd /myproject dir/(when type ls ,I can see apps folder)
> mfp start
> mfp build 
> `

and it doesn't have any response and logs, I think it didn't build all.
any idea about this problem?
Thanks in advance.

**Comment by Hamasn** [comment]
Sorry for missing some information about my MFP project,I am using MFP 7.1 and it is a hybrid project with ionic framework without adapter and procedure.

**Comment by IdanAdar** [comment]
Use "mfp build". Please open questions in StackOverflow, not in GitHub...
