### ISSUE TITLE
JMS adapter Configuration

### ISSUE THREAD

**Issue by sridhar8294** [MobileFirst-Platform-Developer-Center/DevCenter#9]
while calling the adapter file in worklight i'm getting below error.

[ERROR   ] FWLSE0005W: JMS connection exception received: jms/libertyQCF. Closing the connection. [project Adapters]
[ERROR   ] FWLSE0035E: Invocation of procedure 'writeMessage' failed. [project Adapters]
Failed to create connection from factory: jms/libertyQCF

this error i'm getting in console.but i configured in server.xml
   <featureManager>
        <feature>servlet-3.0</feature>
        <feature>jndi-1.0</feature>
        <feature>jdbc-4.0</feature>
        <feature>localConnector-1.0</feature>
        <feature>restConnector-1.0</feature>
        <feature>jsp-2.2</feature>
        <feature>appSecurity-1.0</feature>
        <feature>ssl-1.0</feature>
    </featureManager>  
<messagingEngine id="defaultME">
  <queue forceReliability="ReliablePersistent" id="libertyQ" maxQueueDepth="5000">
  </queue>
  <queue id=""/>
</messagingEngine>
<jmsQueueConnectionFactory connectionManagerRef="ConMgr2" jndiName="jms/libertyQCF">
  <properties.wasJms nonPersistentMapping="ExpressNonPersistent" persistentMapping="ReliablePersistent"/>
  <properties.wasJms/>
</jmsQueueConnectionFactory>
<connectionManager id="ConMrg2" maxPoolSize="2"/>
<jmsQueue jndiName="jms/libertyQue">
  <properties.wasJms deliveryMode="Application" priority="1" queueName="libertyQ" readAhead="AsConnection" timeToLive="500000"/>
</jmsQueue>

**Comment by IdanAdar** [comment]
GitHub is not meant for code support. Open a question on StackOverflow.
